# Generated by Django 6.0.2 on 2026-03-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nexusApp", "0002_faq_pricingplan_planfeature"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("role", models.CharField(max_length=150)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Square crop recommended, minimum 400×400px.",
                        null=True,
                        upload_to="team/",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
